name: Airtable Sync

on:
  workflow_dispatch:

jobs:
  run-sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: node sync.js
        env:
          AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN }}
          BASE_ID: ${{ secrets.BASE_ID }}
